/**
 * @file Learn.tsx
 * @description Renders the educational resource section explaining climate change.
 * Displays counter metrics, Indian emissions breakdown chart, habits quick tips, and links to global initiatives.
 */

import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Tooltip,
  Legend,
} from 'chart.js';
import { Bar } from 'react-chartjs-2';
import { BookOpen } from 'lucide-react';

import { KEY_FACTS, EMISSION_SOURCES, QUICK_TIPS } from '../lib/constants';
import { useLanguage } from '../context/LanguageContext';
import { Card } from '../components/Card';

import FactCard from '../components/learn/FactCard';
import QuickTipCard from '../components/learn/QuickTipCard';
import ResourceCard from '../components/learn/ResourceCard';

ChartJS.register(CategoryScale, LinearScale, BarElement, Tooltip, Legend);

const getLocalizedSourceLabel = (label: string, locale: string) => {
  if (locale === 'en') return label;
  switch (label) {
    case 'Electricity & Heat': return 'बिजली और गर्मी';
    case 'Transport': return 'परिवहन';
    case 'Manufacturing': return 'विनिर्माण';
    case 'Agriculture': return 'कृषि';
    case 'Buildings': return 'भवन';
    default: return label;
  }
};

const RESOURCES_DATA = [
  {
    title: 'UN Climate Action',
    titleHi: 'संयुक्त राष्ट्र जलवायु कार्रवाई',
    desc: 'Official United Nations resource on climate change initiatives and global agreements.',
    descHi: 'जलवायु परिवर्तन पहल और वैश्विक समझौतों पर आधिकारिक संयुक्त राष्ट्र संसाधन।',
    url: 'https://www.un.org/climatechange',
  },
  {
    title: 'NASA Climate',
    titleHi: 'नासा क्लाइमेट',
    desc: "NASA's comprehensive data, evidence, and visualizations on Earth's changing climate.",
    descHi: 'पृथ्वी की बदलती जलवायु पर नासा का व्यापक डेटा, प्रमाण और विज़ुअलाइज़ेशन।',
    url: 'https://climate.nasa.gov',
  },
  {
    title: 'IPCC Reports',
    titleHi: 'आईपीसीसी रिपोर्ट',
    desc: 'Scientific assessments from the Intergovernmental Panel on Climate Change.',
    descHi: 'इंटरगवर्नमेंटल पैनल ऑन क्लाइमेट चेंज (IPCC) से वैज्ञानिक आकलन।',
    url: 'https://www.ipcc.ch',
  },
];

export default function Learn() {
  const { locale, t } = useLanguage();

  const barData = {
    labels: EMISSION_SOURCES.map((s) => getLocalizedSourceLabel(s.label, locale)),
    datasets: [
      {
        label: t('pctTotalEmissions'),
        data: EMISSION_SOURCES.map((s) => s.value),
        backgroundColor: EMISSION_SOURCES.map((s) => s.color),
        borderRadius: 6,
        borderSkipped: false as const,
      },
    ],
  };

  const barOptions = {
    indexAxis: 'y' as const,
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: false },
    },
    scales: {
      x: {
        ticks: { color: '#a1a1aa' },
        grid: { color: '#1a1a1a' },
        max: 40,
      },
      y: {
        ticks: { color: '#a1a1aa', font: { size: 13 } },
        grid: { display: false },
      },
    },
  };

  return (
    <div className="page-wrapper">
      <div className="container">
        <h1 className="page-title">
          <BookOpen size={32} className="icon-green" />
          {locale === 'en' ? 'Learn About ' : ''}
          <span className="text-gradient">
            {locale === 'en' ? 'Climate Change' : 'जलवायु परिवर्तन'}
          </span>
          {locale === 'hi' ? ' के बारे में सीखें' : ''}
        </h1>
        <p className="page-subtitle">
          {t('learnSubtitle')}
        </p>

        {/* ===== What is Carbon Footprint ===== */}
        <Card className="learn-section">
          <h2 className="learn-section-title">{t('whatIsFootprint')}</h2>
          <p className="learn-text">
            {locale === 'en' ? (
              <>
                A <strong>carbon footprint</strong> is the total amount of greenhouse
                gases — primarily carbon dioxide (CO₂) — generated by our actions.
                This includes everything from the energy we use at home, to how we
                travel, what we eat, and what we buy.
              </>
            ) : (
              <>
                एक <strong>कार्बन फुटप्रिंट</strong> हमारे कार्यों द्वारा उत्पन्न ग्रीनहाउस गैसों - मुख्य रूप से carbon dioxide (CO₂) - की कुल मात्रा है।
                इसमें हमारे द्वारा घर पर उपयोग की जाने वाली ऊर्जा से लेकर हमारे यात्रा करने के तरीके, हम क्या खाते हैं और क्या खरीदते हैं, सब कुछ शामिल है।
              </>
            )}
          </p>
          <p className="learn-text">
            {locale === 'en' ? (
              <>
                The average global carbon footprint is about <strong>4.7 tons</strong> per
                person per year. To limit global warming to 1.5°C — the target of the
                Paris Agreement — we need to bring this down to under{' '}
                <strong>2 tons</strong> per person per year by 2050.
              </>
            ) : (
              <>
                औसत वैश्विक कार्बन फुटप्रिंट प्रति वर्ष प्रति व्यक्ति लगभग <strong>4.7 टन</strong> है। ग्लोबल वार्मिंग को 1.5°C तक सीमित करने के लिए — जो पेरिस समझौते का लक्ष्य है — हमें 2050 तक इसे प्रति वर्ष प्रति व्यक्ति <strong>2 टन</strong> से कम करने की आवश्यकता है।
              </>
            )}
          </p>
        </Card>

        {/* ===== Key Facts ===== */}
        <section>
          <h2 className="section-title">
            {locale === 'en' ? 'Key ' : 'मुख्य '}<span className="text-gradient">{locale === 'en' ? 'Facts' : 'तथ्य'}</span>
          </h2>
          <div className="facts-grid">
            {KEY_FACTS.map((fact, i) => (
              <FactCard key={i} fact={fact} />
            ))}
          </div>
        </section>

        {/* ===== Top Emission Sources ===== */}
        <Card className="learn-section">
          <h2 className="learn-section-title">
            {t('topSources')}
          </h2>
          <div className="chart-container chart-container-tall">
            <Bar data={barData} options={barOptions} />
          </div>
        </Card>

        {/* ===== Quick Tips ===== */}
        <section>
          <h2 className="section-title">
            {locale === 'en' ? 'Quick ' : 'त्वरित '}<span className="text-gradient">{locale === 'en' ? 'Tips' : 'सुझाव'}</span>
          </h2>
          <p className="section-subtitle">
            {t('quickTipsSubtitle')}
          </p>
          <div className="tips-grid">
            {QUICK_TIPS.map((tip, i) => (
              <QuickTipCard key={i} tip={tip} />
            ))}
          </div>
        </section>

        {/* ===== Resources ===== */}
        <section>
          <h2 className="section-title">
            {locale === 'en' ? 'Trusted ' : 'विश्वसनीय '}<span className="text-gradient">{locale === 'en' ? 'Resources' : 'संसाधन'}</span>
          </h2>
          <div className="resources-grid">
            {RESOURCES_DATA.map((res) => (
              <ResourceCard key={res.title} resource={res} />
            ))}
          </div>
        </section>
      </div>
    </div>
  );
}
