import { useEffect, useRef, useState, useCallback } from 'react';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Tooltip,
  Legend,
} from 'chart.js';
import { Bar } from 'react-chartjs-2';
import { BookOpen, ExternalLink } from 'lucide-react';

import { KEY_FACTS, EMISSION_SOURCES, QUICK_TIPS } from '../lib/constants';

ChartJS.register(CategoryScale, LinearScale, BarElement, Tooltip, Legend);

/** Animated counter hook */
function useCountUp(target: number, duration = 2000, start = false) {
  const [value, setValue] = useState(0);

  useEffect(() => {
    if (!start) return;
    let startTime: number | null = null;
    let frame: number;

    const animate = (timestamp: number) => {
      if (!startTime) startTime = timestamp;
      const progress = Math.min((timestamp - startTime) / duration, 1);
      setValue(parseFloat((progress * target).toFixed(1)));
      if (progress < 1) {
        frame = requestAnimationFrame(animate);
      }
    };

    frame = requestAnimationFrame(animate);
    return () => cancelAnimationFrame(frame);
  }, [target, duration, start]);

  return value;
}

function FactCard({
  fact,
}: {
  fact: (typeof KEY_FACTS)[number];
}) {
  const ref = useRef<HTMLDivElement>(null);
  const [visible, setVisible] = useState(false);
  const animatedValue = useCountUp(fact.value, 1500, visible);

  const handleIntersection = useCallback((entries: IntersectionObserverEntry[]) => {
    if (entries[0].isIntersecting) {
      setVisible(true);
    }
  }, []);

  useEffect(() => {
    const observer = new IntersectionObserver(handleIntersection, {
      threshold: 0.3,
    });
    const el = ref.current;
    if (el) observer.observe(el);
    return () => {
      if (el) observer.unobserve(el);
    };
  }, [handleIntersection]);

  return (
    <div ref={ref} className="card fact-card">
      <span className="fact-emoji">{fact.icon}</span>
      <div className="fact-value">
        {fact.value >= 100
          ? Math.round(animatedValue)
          : animatedValue.toFixed(1)}
        {fact.suffix}
      </div>
      <p className="fact-label">{fact.label}</p>
    </div>
  );
}

export default function Learn() {
  const barData = {
    labels: EMISSION_SOURCES.map((s) => s.label),
    datasets: [
      {
        label: '% of Total Emissions',
        data: EMISSION_SOURCES.map((s) => s.value),
        backgroundColor: EMISSION_SOURCES.map((s) => s.color),
        borderRadius: 6,
        borderSkipped: false as const,
      },
    ],
  };

  const barOptions = {
    indexAxis: 'y' as const,
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: false },
    },
    scales: {
      x: {
        ticks: { color: '#a1a1aa' },
        grid: { color: '#1a1a1a' },
        max: 40,
      },
      y: {
        ticks: { color: '#a1a1aa', font: { size: 13 } },
        grid: { display: false },
      },
    },
  };

  return (
    <div className="page-wrapper">
      <div className="container">
        <h1 className="page-title">
          <BookOpen size={32} className="icon-green" />
          Learn About <span className="text-gradient">Climate Change</span>
        </h1>
        <p className="page-subtitle">
          Understand carbon footprints, emissions, and what you can do
        </p>

        {/* ===== What is Carbon Footprint ===== */}
        <section className="card learn-section">
          <h2 className="learn-section-title">What is a Carbon Footprint?</h2>
          <p className="learn-text">
            A <strong>carbon footprint</strong> is the total amount of greenhouse
            gases — primarily carbon dioxide (CO₂) — generated by our actions.
            This includes everything from the energy we use at home, to how we
            travel, what we eat, and what we buy.
          </p>
          <p className="learn-text">
            The average global carbon footprint is about <strong>4.7 tons</strong> per
            person per year. To limit global warming to 1.5°C — the target of the
            Paris Agreement — we need to bring this down to under{' '}
            <strong>2 tons</strong> per person per year by 2050.
          </p>
        </section>

        {/* ===== Key Facts ===== */}
        <section>
          <h2 className="section-title">
            Key <span className="text-gradient">Facts</span>
          </h2>
          <div className="facts-grid">
            {KEY_FACTS.map((fact, i) => (
              <FactCard key={i} fact={fact} />
            ))}
          </div>
        </section>

        {/* ===== Top Emission Sources ===== */}
        <section className="card learn-section">
          <h2 className="learn-section-title">
            Top Sources of CO₂ Emissions in India
          </h2>
          <div className="chart-container chart-container-tall">
            <Bar data={barData} options={barOptions} />
          </div>
        </section>

        {/* ===== Quick Tips ===== */}
        <section>
          <h2 className="section-title">
            Quick <span className="text-gradient">Tips</span>
          </h2>
          <p className="section-subtitle">
            Simple changes that make a real difference
          </p>
          <div className="tips-grid">
            {QUICK_TIPS.map((tip, i) => (
              <div key={i} className="card tip-card">
                <span className="tip-emoji">{tip.icon}</span>
                <h3 className="tip-title">{tip.title}</h3>
                <p className="tip-desc">{tip.description}</p>
              </div>
            ))}
          </div>
        </section>

        {/* ===== Resources ===== */}
        <section>
          <h2 className="section-title">
            Trusted <span className="text-gradient">Resources</span>
          </h2>
          <div className="resources-grid">
            {[
              {
                title: 'UN Climate Action',
                desc: 'Official United Nations resource on climate change initiatives and global agreements.',
                url: 'https://www.un.org/climatechange',
              },
              {
                title: 'NASA Climate',
                desc: "NASA's comprehensive data, evidence, and visualizations on Earth's changing climate.",
                url: 'https://climate.nasa.gov',
              },
              {
                title: 'IPCC Reports',
                desc: 'Scientific assessments from the Intergovernmental Panel on Climate Change.',
                url: 'https://www.ipcc.ch',
              },
            ].map((res) => (
              <a
                key={res.title}
                href={res.url}
                target="_blank"
                rel="noopener noreferrer"
                className="card resource-card"
              >
                <h3 className="resource-title">
                  {res.title}
                  <ExternalLink size={16} />
                </h3>
                <p className="resource-desc">{res.desc}</p>
              </a>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
}
