/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useState, useEffect } from 'react';
import type { ReactNode } from 'react';

export type Locale = 'en' | 'hi';

const translations = {
  en: {
    // Nav
    home: 'Home',
    calculator: 'Calculator',
    dashboard: 'Dashboard',
    actions: 'Actions',
    insights: 'Insights',
    learn: 'Learn',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    welcome: 'Welcome to EcoTrack',
    guestMode: 'Guest Mode - Local Data Only',

    // Home
    homeTitle: 'Track & Reduce Your Carbon Footprint',
    homeSubtitle: 'Make data-driven eco-friendly choices. Measure your emissions, get AI-powered insights, and build sustainable habits.',
    startCalculating: 'Start Calculating',
    viewDashboard: 'Go to Dashboard',

    // Calculator
    calcTitle: 'Carbon Footprint Calculator',
    calcSubtitle: 'Answer a few simple questions to estimate your monthly CO2 emissions',
    next: 'Next',
    back: 'Back',
    saveResults: 'Save Results',
    saving: 'Saving...',
    calcSuccess: 'Calculation saved to dashboard!',
    stepTransport: 'Transport',
    stepEnergy: 'Energy',
    stepDiet: 'Diet & Lifestyle',
    stepResults: 'Results',
    yourResults: 'Your Results',
    transportHeader: 'Transportation',
    energyHeader: 'Home Energy',
    dietHeader: 'Diet & Lifestyle',

    // Calculator fields
    commuteMode: 'Primary commute mode',
    dailyDistance: 'Daily commute distance (km)',
    shortFlights: 'Short-haul flights/year (under 3 hours)',
    longFlights: 'Long-haul flights/year (over 3 hours)',
    electricity: 'Monthly electricity consumption (kWh)',
    cookingFuel: 'Primary cooking fuel',
    householdSize: 'Household size (number of people)',
    dietType: 'Diet type',
    onlineOrders: 'Monthly online deliveries (shopping/food)',
    newClothes: 'New clothes purchased per month',

    // Categories
    transport: 'Transport',
    energy: 'Energy',
    diet: 'Diet',
    lifestyle: 'Lifestyle',
    shopping: 'Shopping',
    general: 'General',

    // Dashboard
    dashTitle: 'Your Dashboard',
    dashSubtitle: 'Track your carbon footprint trends and compare with averages',
    score: 'Carbon Score',
    monthly: 'Current Monthly',
    annual: 'Annual Estimate',
    vsIndia: 'vs India Average',
    vsGlobal: 'vs Global Average',
    monthlyTrend: 'Monthly Trend',
    categoryBreakdown: 'Category Breakdown',
    recentHistory: 'Recent History',
    compareFriends: 'Compare with Friends',
    dataSettings: 'Data Settings',
    clearData: 'Clear My Data',
    downloadReport: 'Download Report',
    above: 'Above',
    below: 'Below',
    noDataTitle: 'No Data Yet',
    noDataDesc: 'Calculate your carbon footprint first to see your dashboard with charts and insights.',
    calcFootprintBtn: 'Calculate Your Footprint',

    // Actions
    actionsTitle: 'Eco Action Center',
    actionsSubtitle: 'Adopt green habits and see your annual CO2 savings grow',
    completedCount: 'Actions Completed',
    all: 'All',
    completed: 'Completed',
    notCompleted: 'Not Completed',
    actionSaved: 'Action updated!',

    // Insights
    insightsTitle: 'AI Carbon Insights',
    insightsSubtitle: 'Personalized recommendations generated by Gemini AI based on your footprint',
    shareResults: 'Share Your Results',
    copiedLink: 'Copied dashboard link to clipboard!',

    // Learn
    learnTitle: 'Climate Education',
    learnSubtitle: 'Understand the science, emission sources, and how we can make a difference',
    whatIsFootprint: 'What is a Carbon Footprint?',
    keyFacts: 'Key Facts',
    topSources: 'Top Sources of CO₂ Emissions in India',
    quickTipsTitle: 'Quick Tips',
    quickTipsSubtitle: 'Simple changes that make a real difference',
    trustedResources: 'Trusted Resources',
    pctTotalEmissions: '% of Total Emissions',
  },
  hi: {
    // Nav
    home: 'होम',
    calculator: 'कैलकुलेटर',
    dashboard: 'डैशबोर्ड',
    actions: 'एक्शन्स',
    insights: 'इनसाइट्स',
    learn: 'सीखें',
    signIn: 'साइन इन',
    signOut: 'साइन आउट',
    welcome: 'इकोट्रेक में आपका स्वागत है',
    guestMode: 'अतिथि मोड - केवल स्थानीय डेटा',

    // Home
    homeTitle: 'अपने कार्बन फुटप्रिंट को ट्रैक और कम करें',
    homeSubtitle: 'डेटा-संचालित पर्यावरण-अनुकूल विकल्प चुनें। अपने उत्सर्जन को मापें, एआई-संचालित इनसाइट्स प्राप्त करें, और टिकाऊ आदतें बनाएं।',
    startCalculating: 'गणना शुरू करें',
    viewDashboard: 'डैशबोर्ड पर जाएं',

    // Calculator
    calcTitle: 'कार्बन फुटप्रिंट कैलकुलेटर',
    calcSubtitle: 'अपने मासिक CO2 उत्सर्जन का अनुमान लगाने के लिए कुछ सरल प्रश्नों के उत्तर दें',
    next: 'आगे',
    back: 'पीछे',
    saveResults: 'परिणाम सहेजें',
    saving: 'सहेज रहा है...',
    calcSuccess: 'डैशबोर्ड में गणना सहेजी गई!',
    stepTransport: 'परिवहन',
    stepEnergy: 'ऊर्जा',
    stepDiet: 'आहार और जीवन शैली',
    stepResults: 'परिणाम',
    yourResults: 'आपके परिणाम',
    transportHeader: 'परिवहन',
    energyHeader: 'घरेलू ऊर्जा',
    dietHeader: 'आहार और जीवन शैली',

    // Calculator fields
    commuteMode: 'प्राथमिक यात्रा मोड',
    dailyDistance: 'दैनिक यात्रा दूरी (किमी)',
    shortFlights: 'शॉर्ट-हॉल उड़ानें/वर्ष (3 घंटे से कम)',
    longFlights: 'लॉन्ग-हॉल उड़ानें/वर्ष (3 घंटे से अधिक)',
    electricity: 'मासिक बिजली खपत (kWh)',
    cookingFuel: 'प्राथमिक खाना पकाने का ईंधन',
    householdSize: 'परिवार का आकार (सदस्यों की संख्या)',
    dietType: 'आहार का प्रकार',
    onlineOrders: 'मासिक ऑनलाइन डिलीवरी (शॉपिंग/भोजन)',
    newClothes: 'प्रति माह खरीदे गए नए कपड़े',

    // Categories
    transport: 'परिवहन',
    energy: 'ऊर्जा',
    diet: 'आहार',
    lifestyle: 'जीवन शैली',
    shopping: 'शॉपिंग',
    general: 'सामान्य',

    // Dashboard
    dashTitle: 'आपका डैशबोर्ड',
    dashSubtitle: 'अपने कार्बन फुटप्रिंट के रुझान को ट्रैक करें और औसत के साथ तुलना करें',
    score: 'कार्बन स्कोर',
    monthly: 'वर्तमान मासिक',
    annual: 'वार्षिक अनुमान',
    vsIndia: 'बनाम भारत औसत',
    vsGlobal: 'बनाम वैश्विक औसत',
    monthlyTrend: 'मासिक रुझान',
    categoryBreakdown: 'श्रेणी विवरण',
    recentHistory: 'हाल का इतिहास',
    compareFriends: 'दोस्तों के साथ तुलना',
    dataSettings: 'डेटा सेटिंग्स',
    clearData: 'मेरा डेटा हटाएं',
    downloadReport: 'रिपोर्ट डाउनलोड करें',
    above: 'ऊपर',
    below: 'नीचे',
    noDataTitle: 'अभी तक कोई डेटा नहीं है',
    noDataDesc: 'चार्ट और इनसाइट्स के साथ अपना डैशबोर्ड देखने के लिए पहले अपने कार्बन फुटप्रिंट की गणना करें।',
    calcFootprintBtn: 'अपना फुटप्रिंट मापें',

    // Actions
    actionsTitle: 'इको एक्शन सेंटर',
    actionsSubtitle: 'हरित आदतों को अपनाएं और अपने वार्षिक CO2 बचत को बढ़ते हुए देखें',
    completedCount: 'पूर्ण किए गए एक्शन्स',
    all: 'सभी',
    completed: 'पूर्ण',
    notCompleted: 'अपूर्ण',
    actionSaved: 'एक्शन अपडेट किया गया!',

    // Insights
    insightsTitle: 'एआई कार्बन इनसाइट्स',
    insightsSubtitle: 'आपके फुटप्रिंट के आधार पर जेमिनी एआई द्वारा उत्पन्न व्यक्तिगत सिफारिशें',
    shareResults: 'अपने परिणाम साझा करें',
    copiedLink: 'डैशबोर्ड लिंक क्लिपबोर्ड पर कॉपी किया गया!',

    // Learn
    learnTitle: 'जलवायु शिक्षा',
    learnSubtitle: 'विज्ञान, उत्सर्जन स्रोतों को समझें और जानें कि हम कैसे बदलाव ला सकते हैं',
    whatIsFootprint: 'कार्बन फुटप्रिंट क्या है?',
    keyFacts: 'मुख्य तथ्य',
    topSources: 'भारत में CO₂ उत्सर्जन के मुख्य स्रोत',
    quickTipsTitle: 'त्वरित सुझाव',
    quickTipsSubtitle: 'सरल बदलाव जो वास्तविक अंतर लाते हैं',
    trustedResources: 'विश्वसनीय संसाधन',
    pctTotalEmissions: 'कुल उत्सर्जन का %',
  }
} as const;

interface LanguageContextType {
  locale: Locale;
  t: (key: keyof typeof translations['en']) => string;
  toggleLanguage: () => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(() => {
    try {
      const saved = localStorage.getItem('ecotrack_locale');
      return (saved === 'hi' ? 'hi' : 'en') as Locale;
    } catch {
      return 'en';
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem('ecotrack_locale', locale);
    } catch (e) {
      console.error('Failed to save language setting:', e);
    }
  }, [locale]);

  const toggleLanguage = () => {
    setLocale((prev) => (prev === 'en' ? 'hi' : 'en'));
  };

  const t = (key: keyof typeof translations['en']): string => {
    return translations[locale][key] || translations['en'][key] || String(key);
  };

  return (
    <LanguageContext.Provider value={{ locale, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
